### ISSUE TITLE
is it possible to notify all users?

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/admin_notifications#5]
Is it possible to notify all users? If not, could you implement it? If yes it would be great if it could be restricted to users who have already logged in once.

**Comment by nickvergessen** [comment]
No to both. That is really not what this app is looking at, at the moment.
This here is more of an API endpoint, maybe https://github.com/nextcloud/announcementcenter is more what you want to have?

**Comment by DanScharon** [comment]
I see. Actually I'd rather have a simple way to send notifications to users about upcoming maintenance works than a news blog with its permanent entry and icon within the apps list (which the announcementcenter seems to be). Especially when using the directmenu app it's an additional clutter.

**Comment by Schmuuu** [comment]
Hi,

I have the same use case. I'm already using the "announcement center" as a blog or news site to inform users about future plans and changes, but I was searching for an app that I can use to inform users about an upcoming maintenance in the next few minutes. 

I love this app so far and want to thank you for the good work. If possible however I would even more love it, when there is the possibility to notify all (logged in?) users :)

Will there be a GUI to use as well?

**Comment by nickvergessen** [comment]
As said above and in the other issues, I guess groups and all (logged in)  users make sense and can be implemented (by anyone willing to contribute, its opensource).

Same accounts for a UI, it might make sense, but I have no plan to do this at the moment, since it's not something I need.

You can also use the announcement center for maintenance notifications, just delete the announcement when maintenance is done, that's what I'm doing on my instances and that is the actual feature why I implemented the announcement center in first place.

**Comment by nickvergessen** [comment]
Copied to https://github.com/nextcloud/notifications/issues/121
